# Generated by Django 2.2.24 on 2021-07-19 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0005_auto_20210719_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=200, verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(default='null', upload_to='', verbose_name='Acta Escaneado de Caminata')),
                ('pdf_register', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'PDF',
                'verbose_name_plural': 'Archivos PDF',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_name', models.CharField(max_length=200, verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Prioridad',
                'verbose_name_plural': 'Prioridades',
            },
        ),
        migrations.CreateModel(
            name='WBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wbs_name', models.CharField(max_length=200, verbose_name='WBS')),
                ('state', models.CharField(max_length=1, verbose_name='Estado')),
                ('area', models.CharField(max_length=200, verbose_name='WBS')),
                ('number', models.IntegerField(verbose_name='Código de WBS')),
            ],
            options={
                'verbose_name': 'WBS',
                'verbose_name_plural': 'WBS',
            },
        ),
        migrations.CreateModel(
            name='WalkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historic_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('top', models.CharField(max_length=200, verbose_name='TOP')),
                ('sistem', models.CharField(max_length=200, verbose_name='Sistema')),
                ('subsistem', models.CharField(max_length=200, verbose_name='Sub Sistema')),
                ('walk_number', models.IntegerField(verbose_name='Número de Caminata')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.API', verbose_name='API')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Contract', verbose_name='Contrato')),
                ('wbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkreport.WBS', verbose_name='WBS')),
            ],
            options={
                'verbose_name': 'Reporte de Caminata',
                'verbose_name_plural': 'Reportes de Caminata',
            },
        ),
        migrations.CreateModel(
            name='WalkObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubication', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('plane_number', models.IntegerField(verbose_name='Número de Plano')),
                ('equipment_code', models.IntegerField(verbose_name='Codigo de Equipo')),
                ('action_description', models.TextField(blank=True, default='', verbose_name='Descripción Acción Pendiente')),
                ('historic_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('stipulated_date', models.DateField(verbose_name='Fecha de Compromiso de Cierre')),
                ('real_close_date', models.DateField(verbose_name='Fecha de Cierre Real')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkreport.Discipline', verbose_name='Disciplina')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leader', to=settings.AUTH_USER_MODEL, verbose_name='Lider de Caminata')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkreport.Priority', verbose_name='Prioridad')),
                ('register_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_register_by', to=settings.AUTH_USER_MODEL, verbose_name='Originado por')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Construccción')),
                ('walk_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkreport.WalkReport', verbose_name='Reporte de Caminata')),
            ],
            options={
                'verbose_name': 'Observación de Caminata',
                'verbose_name_plural': 'Observaciones de Caminata',
            },
        ),
        migrations.CreateModel(
            name='FileWalkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro de PDF')),
                ('evidence_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkreport.EvidenceFile', verbose_name='Evidencia de Archivo')),
                ('walk_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkreport.WalkReport', verbose_name='Reporte de Caminata')),
            ],
            options={
                'verbose_name': 'Reporte de Archivo de Caminata',
                'verbose_name_plural': 'Reportes de Archivo de Caminata',
            },
        ),
    ]
