# Generated by Django 2.2.24 on 2021-07-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkreport', '0002_auto_20210721_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfwalkreport',
            name='upload',
            field=models.FileField(default='null', upload_to='pdf_walk_reports', verbose_name='PDF'),
        ),
    ]
