# Generated by Django 2.2.24 on 2021-10-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_contract_enterprise_contract'),
        ('walkreport', '0003_auto_20210722_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkreport',
            name='sistem_walk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.Sistem', verbose_name='Sistema'),
        ),
        migrations.AddField(
            model_name='walkreport',
            name='subsistem_walk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.Subsistem', verbose_name='Subsistema'),
        ),
    ]
