# Generated by Django 2.2.24 on 2021-10-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkreport', '0004_auto_20211021_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkobservation',
            name='real_close_date',
            field=models.DateField(blank=True, verbose_name='Fecha de Cierre Real'),
        ),
    ]
