# Generated by Django 2.2.24 on 2021-11-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20211103_1543'),
        ('walkreport', '0006_auto_20211021_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkreport',
            name='sistem_walk',
        ),
        migrations.RemoveField(
            model_name='walkreport',
            name='subsistem_walk',
        ),
        migrations.AddField(
            model_name='walkreport',
            name='sistem_subsistem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.SistemSubSistem', verbose_name='Sistema'),
            preserve_default=False,
        ),
    ]
