# Generated by Django 2.1.15 on 2021-12-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walkreport', '0008_auto_20211103_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkreport',
            name='sistem',
        ),
        migrations.RemoveField(
            model_name='walkreport',
            name='subsistem',
        ),
    ]
