# Generated by Django 2.2.18 on 2021-03-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100, verbose_name='Nombre Actividad')),
                ('start_date', models.DateField(verbose_name='Comienza el')),
                ('finish_date', models.DateField(verbose_name='Finaliza el')),
                ('state', models.CharField(max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_number', models.CharField(max_length=100, verbose_name='Número de API')),
                ('project_name', models.CharField(max_length=100, verbose_name='Nombre de Proyecto')),
                ('start_date', models.DateField(verbose_name='Comienza el')),
                ('finish_date', models.DateField(verbose_name='Finaliza el')),
                ('state', models.CharField(max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'API',
                'verbose_name_plural': 'API',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.IntegerField(verbose_name='Número de Contrato')),
                ('enterprise', models.CharField(max_length=150, verbose_name='Empresa Contratista')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('project_boss', models.CharField(max_length=12, verbose_name='Jefe de Proyecto')),
                ('email', models.CharField(max_length=12, verbose_name='Correo')),
                ('cellphone', models.CharField(max_length=12, verbose_name='Celular')),
                ('start_date', models.DateField(verbose_name='Comienza el')),
                ('finish_date', models.DateField(verbose_name='Finaliza el')),
                ('state', models.CharField(max_length=1, verbose_name='Estado')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.API', verbose_name='API')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_name', models.CharField(max_length=100, verbose_name='¿Seguimiento?')),
                ('state', models.CharField(max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
            },
        ),
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_amount', models.DecimalField(decimal_places=3, max_digits=10, max_length=100, verbose_name='Cantidad Real')),
                ('inspection_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inspección')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Activity', verbose_name='Actividad')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.API', verbose_name='API')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Contract', verbose_name='Contrato')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Following', verbose_name='Seguimiento')),
            ],
            options={
                'verbose_name': 'Historico',
                'verbose_name_plural': 'Historicos',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='URL de la imagén')),
                ('created_at', models.DateTimeField(verbose_name='Creado el')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_name', models.CharField(max_length=100, verbose_name='Medida')),
            ],
            options={
                'verbose_name': 'Medida',
                'verbose_name_plural': 'Medidas',
            },
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonconformity_name', models.CharField(max_length=100, verbose_name='¿Conformidad?')),
                ('state', models.CharField(max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'No Conformidad',
                'verbose_name_plural': 'No Conformidades',
            },
        ),
        migrations.CreateModel(
            name='Precondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precondition_name', models.CharField(max_length=100, verbose_name='Prerequisito')),
                ('state', models.CharField(max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Prerrequisito',
                'verbose_name_plural': 'Prerrequisitos',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=100, verbose_name='Referencia')),
                ('state', models.CharField(max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('state', models.CharField(max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='SubActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subactivity_name', models.CharField(max_length=100, verbose_name='Nombre de Proyecto')),
                ('measure', models.CharField(max_length=10, verbose_name='Medida')),
                ('average_amount', models.DecimalField(decimal_places=3, max_digits=10, max_length=50, verbose_name='Cantidad Promedio')),
                ('average_hh', models.DecimalField(decimal_places=3, max_digits=10, max_length=50, verbose_name='Promedio HH')),
                ('start_date', models.DateField(verbose_name='Comienza el')),
                ('finish_date', models.DateField(verbose_name='Finaliza el')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Activity', verbose_name='Actividad')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.API', verbose_name='API')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'SubActividad',
                'verbose_name_plural': 'SubActividades',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Prerequisito')),
                ('historical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Historical', verbose_name='Historico')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Reference', verbose_name='Referencia')),
            ],
            options={
                'verbose_name': 'Prerrequisito',
                'verbose_name_plural': 'Prerrequisitos',
            },
        ),
        migrations.AddField(
            model_name='historical',
            name='images',
            field=models.ManyToManyField(blank=True, to='report.Image', verbose_name='Imagenes'),
        ),
        migrations.AddField(
            model_name='historical',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Measure', verbose_name='Medida'),
        ),
        migrations.AddField(
            model_name='historical',
            name='nonconformity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.NonConformity', verbose_name='No Conformidad'),
        ),
        migrations.AddField(
            model_name='historical',
            name='precondition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Precondition', verbose_name='Pre requisito'),
        ),
        migrations.AddField(
            model_name='historical',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Specialty', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='historical',
            name='subactivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.SubActivity', verbose_name='Sub Actividad'),
        ),
        migrations.AddField(
            model_name='activity',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.API', verbose_name='API'),
        ),
        migrations.AddField(
            model_name='activity',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Contract', verbose_name='Contrato'),
        ),
    ]
