# Generated by Django 2.2.19 on 2021-06-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical',
            name='difference',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, max_length=100, verbose_name='Total Restante'),
        ),
        migrations.AddField(
            model_name='subactivity',
            name='days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Días a trabajar'),
        ),
    ]
