# Generated by Django 2.2.18 on 2021-03-09 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type_name', models.CharField(max_length=200, verbose_name='Nombre del Tipo de Actividad')),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipo de Actividades',
            },
        ),
        migrations.AddField(
            model_name='historical',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Inspector del Informe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subactivity',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.ActivityType', verbose_name='Tipo de Actividad'),
            preserve_default=False,
        ),
    ]
