# Generated by Django 2.2.24 on 2021-06-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210602_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='subactivity',
            name='ref_day',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, max_length=100, verbose_name='Referencia Diaria'),
        ),
    ]
