# Generated by Django 2.2.24 on 2021-06-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_subactivity_ref_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Proyecto'),
        ),
        migrations.AlterField(
            model_name='api',
            name='state',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cellphone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='email',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='enterprise',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa Contratista'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project_boss',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Jefe de Proyecto'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
