# Generated by Django 2.2.24 on 2021-07-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210615_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project_boss',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Jefe de Proyecto'),
        ),
    ]
