# Generated by Django 2.2.24 on 2021-10-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_enterprise_sistem_subsistem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='enterprise_contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.Enterprise', verbose_name='Empresa Contratista'),
        ),
    ]
