# Generated by Django 2.2.24 on 2021-11-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_contract_enterprise_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsistem',
            name='sistem',
        ),
        migrations.CreateModel(
            name='SistemSubSistem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Sistem', verbose_name='Sistema')),
                ('subsistem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Subsistem', verbose_name='Sub Sistema')),
            ],
            options={
                'verbose_name': 'Subsistema',
                'verbose_name_plural': 'Sub Sistemas',
            },
        ),
    ]
