# Generated by Django 2.2.24 on 2021-11-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20211103_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistemsubsistem',
            options={'verbose_name': 'Subsistema del Sistema', 'verbose_name_plural': 'Subsistema de los Sistemas'},
        ),
    ]
