# Generated by Django 2.1.15 on 2021-12-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20211103_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise_rut',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='RUT de Empresa'),
        ),
    ]
