# Generated by Django 2.2.24 on 2021-08-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iscreport', '0001_initial'),
    ]

    operations = [
    ]
