# Generated by Django 2.1.15 on 2021-11-16 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0009_auto_20211103_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Grupo de Calidad en Contrato',
                'verbose_name_plural': 'Grupo de Calidad en Contrato',
            },
        ),
        migrations.CreateModel(
            name='ISCFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(default='null', upload_to='evidence_isc_list', verbose_name='File')),
                ('file_register', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro de Archivo')),
            ],
            options={
                'verbose_name': 'Archivo de lista ISC',
                'verbose_name_plural': 'Archivos de lista ISC',
            },
        ),
        migrations.CreateModel(
            name='ISCList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative', models.IntegerField(verbose_name='Correlativo')),
                ('num_audit', models.IntegerField(verbose_name='N° de Auditoria')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.API', verbose_name='API')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Contract', verbose_name='Contrato')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario registrador')),
            ],
            options={
                'verbose_name': 'Lista de Verificacion ISC',
                'verbose_name_plural': 'Listas de Verificacion ISC',
            },
        ),
        migrations.CreateModel(
            name='ISCPDFFIle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(default='null', upload_to='pdf_isc_list', verbose_name='PDF')),
                ('file_register', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro de PDF')),
            ],
            options={
                'verbose_name': 'Reporte PDF',
                'verbose_name_plural': 'Reportes PDF',
            },
        ),
        migrations.CreateModel(
            name='ISCReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.ISCFile', verbose_name='Archivo de Lista ISC')),
                ('isc_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.ISCList', verbose_name='Lista ISC')),
            ],
            options={
                'verbose_name': 'Repertorio de Archivos en Lista ISC',
                'verbose_name_plural': 'Repertorios de Archivos en Lista ISC',
            },
        ),
        migrations.CreateModel(
            name='ISCReportPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isc_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.ISCList', verbose_name='Lista ISC')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.ISCPDFFIle', verbose_name='Reporte PDF')),
            ],
            options={
                'verbose_name': 'Repertorio de PDF en Lista ISC',
                'verbose_name_plural': 'Repertorios de PDF en Lista ISC',
            },
        ),
        migrations.CreateModel(
            name='QualityContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplishment', models.BooleanField()),
                ('verification_method', models.CharField(blank=True, max_length=250, null=True, verbose_name='Metodo de Verificación')),
                ('audit_result', models.CharField(blank=True, max_length=250, null=True, verbose_name='Resultado de Auditoría')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Requisito de Calidad en Contrato',
                'verbose_name_plural': 'Requisitos de Calidad en Contrato',
            },
        ),
        migrations.CreateModel(
            name='QualityRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=250, verbose_name='Requisito de Calidad')),
                ('reference', models.CharField(max_length=250, verbose_name='Referencia ISO')),
            ],
            options={
                'verbose_name': 'Grupo de requisitos de Calidad',
                'verbose_name_plural': 'Grupos de requisitos de Calidad',
            },
        ),
        migrations.CreateModel(
            name='QualityRequirementGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_group_name', models.CharField(max_length=250, verbose_name='Nombre del grupo de Calidad')),
            ],
            options={
                'verbose_name': 'Grupo de requisitos de Calidad',
                'verbose_name_plural': 'Grupos de requisitos de Calidad',
            },
        ),
        migrations.AddField(
            model_name='qualityrequirement',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.QualityRequirementGroup', verbose_name='Grupo de Calidad'),
        ),
        migrations.AddField(
            model_name='qualitycontract',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.QualityRequirement', verbose_name='Requisito de Calidad'),
        ),
        migrations.AddField(
            model_name='groupcontract',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.QualityRequirementGroup', verbose_name='Grupo de Calidad'),
        ),
    ]
