# Generated by Django 2.2.24 on 2021-08-09 17:11

from django.db import migrations, models
import django.db.models.deletion
import pandas as pd


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0005_auto_20210719_1138'),
    ]

    def insert_init_data(apps, schema_editor):

        dfgroup = pd.read_csv('iscreport/grouprequisitos.csv', encoding='latin-1',sep=";")
        df = pd.read_csv('iscreport/requisitoscalidad.csv', encoding='latin-1',sep=";")

        QualityRequirement = apps.get_model('iscreport', 'QualityRequirement')
        QualityGroup = apps.get_model('iscreport', 'QualityRequirementGroup')

        for g in dfgroup:
            QualityGroup.objects.create(
                    requirement_group_name = i['requirement_group_name']
                )

        for i in df:
            QualityRequirement.objects.create(
                    requirement_name = i['requirement_name'],
                    reference = i['reference'],
                    group = int(i['id_qualityrequirementgroup'])
                )


    def undo_insert_data(apps, schema_editor):

        QualityRequirement = apps.get_model('iscreport', 'QualityRequirement')
        QualityRequirement.objects.all().delete()

        QualityGroup = apps.get_model('iscreport', 'QualityRequirementGroup')
        QualityGroup.objects.all().delete()



    operations = [
        migrations.CreateModel(
            name='ISCFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(default='null', upload_to='evidence_isc_list', verbose_name='File')),
                ('file_register', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro de Archivo')),
            ],
            options={
                'verbose_name': 'Archivo de lista ISC',
                'verbose_name_plural': 'Archivos de lista ISC',
            },
        ),
        migrations.CreateModel(
            name='ISCList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative', models.IntegerField(verbose_name='Correlativo')),
                ('num_audit', models.IntegerField(verbose_name='N° de Auditoria')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.API', verbose_name='API')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Lista de Verificacion ISC',
                'verbose_name_plural': 'Listas de Verificacion ISC',
            },
        ),
        migrations.CreateModel(
            name='QualityRequirementGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_group_name', models.CharField(max_length=250, verbose_name='Nombre del grupo de Calidad')),
            ],
            options={
                'verbose_name': 'Grupo de requisitos de Calidad',
                'verbose_name_plural': 'Grupos de requisitos de Calidad',
            },
        ),
        migrations.CreateModel(
            name='QualityRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(max_length=250, verbose_name='Requisito de Calidad')),
                ('reference', models.CharField(max_length=250, verbose_name='Referencia ISO')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.QualityRequirementGroup', verbose_name='Grupo de Calidad')),
            ],
            options={
                'verbose_name': 'Grupo de requisitos de Calidad',
                'verbose_name_plural': 'Grupos de requisitos de Calidad',
            },
            
        ),
        migrations.RunPython(insert_init_data, reverse_code=undo_insert_data),
        migrations.CreateModel(
            name='QualityContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplishment', models.BooleanField()),
                ('verification_method', models.CharField(blank=True, max_length=250, null=True, verbose_name='Metodo de Verificación')),
                ('audit_result', models.CharField(blank=True, max_length=250, null=True, verbose_name='Resultado de Auditoría')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Contract', verbose_name='Contrato')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.QualityRequirement', verbose_name='Requisito de Calidad')),
            ],
            options={
                'verbose_name': 'Requisito de Calidad en Contrato',
                'verbose_name_plural': 'Requisitos de Calidad en Contrato',
            },
        ),
        migrations.CreateModel(
            name='ISCReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.ISCFile', verbose_name='Archivo de Lista ISC')),
                ('isc_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.ISCList', verbose_name='Lista ISC')),
            ],
            options={
                'verbose_name': 'Repertorio de Archivos en Lista ISC',
                'verbose_name_plural': 'Repertorios de Archivos en Lista ISC',
            },
        ),
        migrations.CreateModel(
            name='GroupContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Contract', verbose_name='Contrato')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.QualityRequirementGroup', verbose_name='Grupo de Calidad')),
            ],
            options={
                'verbose_name': 'Grupo de Calidad en Contrato',
                'verbose_name_plural': 'Grupo de Calidad en Contrato',
            },
        ),
    ]
