# Generated by Django 2.2.24 on 2021-08-10 03:02
from django.db import migrations, models
import django.db.models.deletion
import pandas as pd
from iscreport.models import QualityRequirementGroup, QualityRequirement


class Migration(migrations.Migration):

    dependencies = [
        ('iscreport', '0002_auto_20210809_2300'),
    ]

    #def insert_init_data(apps, schema_editor):

    #    dfgroup = pd.read_csv('iscreport/grouprequisitos.csv', encoding='latin-1',sep=",")
    #    df = pd.read_csv('iscreport/requisitoscalidad.csv', encoding='latin-1',sep=";")

    #    QualityRequirement = apps.get_model('iscreport', 'QualityRequirement')
    #    QualityGroup = apps.get_model('iscreport', 'QualityRequirementGroup')

    #    for _, row in dfgroup.iterrows():

    #        groups = QualityRequirementGroup(
    #                requirement_group_name = row.grupo
    #            )
    #        groups.save()

    #    for _, row in df.iterrows():

    #        qualities = QualityRequirement(
    #                requirement_name = df.nombre_requisito,
    #                reference = df.referencia,
    #                group_id = df.id_grupo.astype(int)
    #            )
    #        qualities.save()

    #def undo_insert_data(apps, schema_editor):

    #    QualityRequirement = apps.get_model('iscreport', 'QualityRequirement')
    #    QualityRequirement.objects.all().delete()

    #    QualityGroup = apps.get_model('iscreport', 'QualityRequirementGroup')
    #    QualityGroup.objects.all().delete()

    operations = [
        #migrations.RunPython(insert_init_data, reverse_code=undo_insert_data)
    ]
