# Generated by Django 2.2.24 on 2021-09-01 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iscreport', '0003_auto_20210809_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='isclist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario registrador'),
        ),
    ]
