# Generated by Django 2.2.24 on 2021-09-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iscreport', '0004_isclist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISCPDFFIle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(default='null', upload_to='pdf_isc_list', verbose_name='PDF')),
                ('file_register', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro de PDF')),
            ],
            options={
                'verbose_name': 'Reporte PDF',
                'verbose_name_plural': 'Reportes PDF',
            },
        ),
        migrations.CreateModel(
            name='ISCReportPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isc_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.ISCList', verbose_name='Lista ISC')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscreport.ISCPDFFIle', verbose_name='Reporte PDF')),
            ],
            options={
                'verbose_name': 'Repertorio de PDF en Lista ISC',
                'verbose_name_plural': 'Repertorios de PDF en Lista ISC',
            },
        ),
    ]
