# Generated by Django 2.2.24 on 2021-07-28 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report', '0005_auto_20210719_1138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walkreport', '0003_auto_20210722_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('image', models.ImageField(default='null', upload_to='nonconformity_evidences', verbose_name='Miniatura')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='NonConformityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_audit', models.IntegerField(verbose_name='N° de Auditoria')),
                ('item', models.IntegerField(verbose_name='Item')),
                ('correlative', models.IntegerField(verbose_name='Correlativo')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('criticality', models.IntegerField(verbose_name='Criticidad de No Conformidad')),
                ('origin', models.CharField(max_length=200, verbose_name='Origen')),
                ('clasification', models.CharField(max_length=200, verbose_name='Clasificación')),
                ('infringement_requirement', models.TextField(blank=True, verbose_name='Requisito Incumplido')),
                ('details', models.TextField(blank=True, verbose_name='Detalles de la No Conformidad')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('reference_documents', models.TextField(blank=True, verbose_name='Criterio / Documento de Referencia')),
                ('ncr_standar', models.CharField(max_length=200, verbose_name='Criterio Específico de NCR')),
                ('num_transmital_ncr', models.IntegerField(verbose_name='N° Transmital Envio NCR')),
                ('num_transmital_action', models.IntegerField(verbose_name='N° Transmital Envío Acción Correctiva')),
                ('num_ncr', models.IntegerField(verbose_name='N° NCR Emitida')),
                ('status', models.CharField(max_length=200, verbose_name='Estatus')),
                ('stipulated_date', models.DateField(verbose_name='Fecha de Compromiso de Cierre')),
                ('real_close_date', models.DateField(verbose_name='Fecha de Cierre Real')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.API', verbose_name='API')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Contract', verbose_name='Contrato')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkreport.Discipline', verbose_name='Disciplina')),
                ('register_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_originated_by', to=settings.AUTH_USER_MODEL, verbose_name='Originado por')),
                ('wbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkreport.WBS', verbose_name='WBS')),
            ],
            options={
                'verbose_name': 'Reporte de No Conformidad',
                'verbose_name_plural': 'Reportes de No Conformidad',
            },
        ),
        migrations.CreateModel(
            name='NonConformityReportImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformityreport.NonConformityImage', verbose_name='Image')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformityreport.NonConformityReport', verbose_name='Reporte de No Conformidad')),
            ],
            options={
                'verbose_name': 'Reporte de Imagen',
                'verbose_name_plural': 'Reporte de Imagenes',
            },
        ),
    ]
