# Generated by Django 2.2.24 on 2021-07-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformityreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformityreport',
            name='sistem',
            field=models.CharField(default='', max_length=200, verbose_name='Sistema'),
        ),
        migrations.AddField(
            model_name='nonconformityreport',
            name='subsistem',
            field=models.CharField(default='', max_length=200, verbose_name='Subsistema'),
        ),
    ]
