# Generated by Django 2.2.24 on 2021-08-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformityreport', '0002_auto_20210728_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformityreport',
            name='tag',
            field=models.CharField(default='', max_length=200, verbose_name='Tag'),
        ),
    ]
