# Generated by Django 2.2.24 on 2021-08-03 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformityreport', '0003_nonconformityreport_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonConformityPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(default='null', upload_to='pdf_nonconformity_reports', verbose_name='PDF')),
                ('pdf_register', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro de PDF')),
            ],
            options={
                'verbose_name': 'PDF Reporte de No Conformidad',
                'verbose_name_plural': 'Archivos PDF Reporte de No Conformidad',
            },
        ),
        migrations.CreateModel(
            name='NonConformityReportPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro de PDF')),
                ('noncon_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformityreport.NonConformityReport', verbose_name='Reporte de No Conformidad')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonconformityreport.NonConformityPDF', verbose_name='PDF de Reporte de No Conformidad')),
            ],
            options={
                'verbose_name': 'Repertorio de PDF de Reporte de No Conformidad',
                'verbose_name_plural': 'Repertorios de Archivos PDF Reporte de No Conformidad',
            },
        ),
    ]
